In [4]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
import numpy as np
a = np.ones(20)*2
b = np.arange(1, 21, 1)
print((a ** b) / b)

[  2.00000000e+00   2.00000000e+00   2.66666667e+00   4.00000000e+00
   6.40000000e+00   1.06666667e+01   1.82857143e+01   3.20000000e+01
   5.68888889e+01   1.02400000e+02   1.86181818e+02   3.41333333e+02
   6.30153846e+02   1.17028571e+03   2.18453333e+03   4.09600000e+03
   7.71011765e+03   1.45635556e+04   2.75941053e+04   5.24288000e+04]


**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
import numpy as np
i = np.arange(6)
a = np.ones(6)*0.1
b = np.ones(6)*0.2
s1 = np.ones(6)*3
s2 = np.ones(6)*4
print(np.sum((a ** (s1 * i))*(b ** (s2 * i))))

1.0000016


**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [11]:
import numpy as np
a = np.zeros((8, 8))
a[::2, ::2] = 1
a[1::2, 1::2] = 1
print(a)

[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [7]:
import numpy as np
X = np.random.random((5, 2))
print(X)
Y = np.zeros((5, 2), dtype='float64')
Y[:, 0] = np.sqrt(((X[:, 0] ** 2) + (X[:, 1] ** 2)))
Y[:, 1] = np.arctan((X[:, 1] / X[:, 0]))
print(Y)

[[ 0.09205797  0.77073226]
 [ 0.41810745  0.98467124]
 [ 0.35194712  0.16642906]
 [ 0.15264509  0.1069681 ]
 [ 0.97591414  0.55429466]]
[[ 0.77621059  1.45191731]
 [ 1.06976226  1.16925073]
 [ 0.38931402  0.44171791]
 [ 0.18639393  0.61123816]
 [ 1.12234174  0.51653865]]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [42]:
X = np.random.random((10, 10))
print(X)
print(X.argmax())
print((X.argmax() // X.shape[1]), (X.argmax() % X.shape[1]))


[[ 0.35195429  0.67989925  0.38377185  0.41180926  0.58149829  0.20748749
   0.06323383  0.98578916  0.24441979  0.98473455]
 [ 0.89525996  0.41736291  0.35216902  0.55928727  0.08042927  0.70667031
   0.32259378  0.395341    0.59764166  0.37038059]
 [ 0.10022028  0.51051162  0.91127539  0.83875788  0.32078502  0.31495023
   0.09638836  0.16129719  0.34052441  0.01939693]
 [ 0.34592468  0.63781939  0.84100749  0.71881482  0.29280258  0.95014999
   0.66363273  0.56378202  0.5903458   0.09193675]
 [ 0.98723555  0.57753631  0.74499413  0.25789397  0.03725063  0.95618007
   0.90169249  0.55263206  0.66216097  0.46108902]
 [ 0.88526211  0.03962123  0.42263649  0.80013143  0.76142368  0.72803412
   0.19556606  0.63253061  0.67645657  0.19779058]
 [ 0.7891852   0.98979165  0.62158339  0.41522519  0.94838797  0.08949719
   0.1951297   0.3981719   0.52047568  0.5356694 ]
 [ 0.73322821  0.3502689   0.08367473  0.98593946  0.61317732  0.16711506
   0.82471747  0.03241483  0.77941989  0.38151087]


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [18]:
import numpy as np
X = np.random.random((10, 2))
y = np.random.random((1, 2))

print(X)
print(y)
print(X[np.argmin(np.sqrt(((X[:, 0] - y[0][0]) ** 2) + ((X[:, 1] - y[0][1]) ** 2)))])

[[ 0.19090311  0.03681683]
 [ 0.49393164  0.88906476]
 [ 0.24495315  0.78128728]
 [ 0.48053267  0.29124592]
 [ 0.84088746  0.94156133]
 [ 0.07501839  0.27718209]
 [ 0.43616081  0.28050843]
 [ 0.24079457  0.78798911]
 [ 0.40059711  0.06037366]
 [ 0.79245192  0.19205588]]
[[ 0.35659052  0.22307674]]
[ 0.43616081  0.28050843]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [13]:
import numpy as np
@np.vectorize
def foo(x):
    if x < 0:
        return (x ** 2) + 2*x + 6
    elif ((x >= 0) and (x <= 2)):
        return x+6
    else:
        return (x ** 2) + 4*x - 4
a = np.arange(-3, 4, 1)
print(a)
print(foo(a))

[-3 -2 -1  0  1  2  3]
[ 9  6  5  6  7  8 17]


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [41]:
X = np.random.random((10, 10))
print(X-np.reshape(np.mean(X, axis=1), (np.mean(X, axis=1).size, 1)))
print(np.mean(X-np.reshape(np.mean(X, axis=1), (np.mean(X, axis=1).size, 1)), axis=1))

[[-0.42616909  0.2251115  -0.1845864   0.37621825 -0.1035115  -0.06359585
   0.36842033  0.02668062 -0.05022529 -0.16834257]
 [ 0.33845857 -0.10675786  0.051723    0.17597544  0.02826584  0.24181411
   0.03386131 -0.2012066  -0.15229519 -0.40983863]
 [-0.28481876 -0.17908692  0.18988147  0.26915863  0.21747187 -0.30353024
   0.31664461  0.07199237 -0.36336049  0.06564746]
 [ 0.44549495 -0.34395054  0.33978307 -0.42955151 -0.43843401 -0.3997912
   0.21004617 -0.18498253  0.54802009  0.2533655 ]
 [ 0.27688497 -0.31194682  0.0142088   0.20261146 -0.14662782  0.29983168
  -0.30629848  0.1215549   0.18794018 -0.33815887]
 [-0.31344918 -0.38798808  0.31280161  0.5217486  -0.11798127  0.04213638
  -0.19520599 -0.06532539  0.25385926 -0.05059594]
 [-0.23087804 -0.18486017  0.0429948  -0.23768115 -0.15143391 -0.10975929
   0.46107178  0.21674091 -0.00943586  0.20324093]
 [ 0.39140117 -0.24041429  0.1488197  -0.13486151 -0.18712878 -0.11542691
  -0.18803061  0.00865621  0.30227605  0.01470897]
 

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [43]:
X = np.random.normal(loc=5, scale=2., size=1000)
#print(X)
import numpy as np
m = np.sum(X) / X.size
print(m)
s = np.sum((X-m) ** 2) / X.size
print(s)



5.0028958475
3.94321471674


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [40]:
def f(i, j):
    return (i + j) % 5 
b = np.fromfunction(f,(5,5),dtype=int)
print(b)

[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]
